# Generated by Django 2.2.4 on 2020-05-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userdetail',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
